# Generated by Django 4.2.1 on 2025-07-27 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalog', '0004_article_category_article_subcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='show_on_landing_page',
            field=models.BooleanField(default=False),
        ),
    ]
