# Generated by Django 4.2.1 on 2025-07-27 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalog', '0005_article_show_on_landing_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='show_on_landing_page',
            field=models.BooleanField(default=False),
        ),
    ]
