# Generated by Django 4.2.1 on 2025-07-27 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalog', '0006_category_show_on_landing_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='sizes_available',
            field=models.JSONField(default=list, help_text='Available sizes for this article'),
        ),
    ]
