# Generated by Django 4.2.1 on 2025-07-28 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalog', '0007_article_sizes_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='deliver_to',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
