# Generated by Django 5.2.4 on 2025-07-29 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalog', '0008_order_confirmed_order_deliver_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='canclation_reason',
            field=models.CharField(max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='cancled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
    ]
